// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Data
type Data struct {
	Location             string            `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Values               map[string]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Data) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Write result
type Result struct {
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "services.Data")
	proto.RegisterMapType((map[string]string)(nil), "services.Data.ValuesEntry")
	proto.RegisterType((*Result)(nil), "services.Result")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor_b90fe3356ea5df07) }

var fileDescriptor_b90fe3356ea5df07 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0xbb, 0x80, 0x2b, 0x4e, 0x93, 0xda, 0x4c, 0x8c, 0xd9, 0x70, 0x22, 0x9c, 0x38, 0x34,
	0x1c, 0xf0, 0xa2, 0xbd, 0x8a, 0x2f, 0x80, 0xd1, 0xfb, 0xb4, 0x4c, 0x4c, 0x23, 0x96, 0x86, 0x1d,
	0x9a, 0xf4, 0x31, 0x7c, 0x28, 0xdf, 0xcb, 0xb0, 0x50, 0xff, 0x5e, 0x7a, 0xdb, 0xdf, 0xec, 0xf7,
	0x7d, 0xfb, 0x6d, 0x06, 0x66, 0x15, 0x09, 0xad, 0xc8, 0x72, 0xb6, 0x6b, 0x1b, 0x69, 0x30, 0xb4,
	0xdc, 0xee, 0x37, 0x6b, 0xb6, 0xc9, 0xbb, 0x82, 0xa0, 0x20, 0x21, 0x8c, 0x20, 0xac, 0x9b, 0x35,
	0xc9, 0xa6, 0xd9, 0x1a, 0x15, 0xab, 0xf4, 0xa2, 0xfc, 0x62, 0xcc, 0x41, 0xef, 0xa9, 0xee, 0xd8,
	0x1a, 0x2f, 0xf6, 0xd3, 0x69, 0x1e, 0x65, 0x47, 0x7f, 0xd6, 0x7b, 0xb3, 0x67, 0x77, 0xf9, 0xb0,
	0x95, 0xf6, 0x50, 0x8e, 0xca, 0xe8, 0x0e, 0xa6, 0x3f, 0xc6, 0x38, 0x07, 0xff, 0x95, 0x0f, 0x63,
	0x72, 0x7f, 0xc4, 0x2b, 0x38, 0x73, 0x52, 0xe3, 0xb9, 0xd9, 0x00, 0x4b, 0xef, 0x56, 0x25, 0x4b,
	0xd0, 0x25, 0xdb, 0xae, 0x16, 0xbc, 0x06, 0x6d, 0x85, 0xa4, 0xb3, 0xc6, 0x8f, 0x55, 0x1a, 0x96,
	0x23, 0xa1, 0x81, 0xf3, 0x37, 0xb6, 0x96, 0x5e, 0xd8, 0x04, 0xce, 0x7d, 0xc4, 0xfc, 0x43, 0xc1,
	0x65, 0x31, 0x7e, 0xf6, 0x71, 0x28, 0x89, 0x0b, 0xd0, 0xf7, 0x2d, 0x93, 0x30, 0xce, 0x7e, 0x17,
	0x8f, 0xe6, 0xdf, 0x3c, 0xbc, 0x98, 0x4c, 0x30, 0x85, 0xa0, 0x64, 0xaa, 0xfe, 0x69, 0xff, 0x70,
	0x32, 0xe9, 0x73, 0x9f, 0x76, 0xd5, 0xa9, 0xb9, 0x0b, 0xd0, 0x05, 0xd7, 0x7c, 0x9a, 0x7a, 0xa5,
	0xdd, 0xa2, 0x6e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xfb, 0x14, 0xd1, 0xba, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabaseServiceClient interface {
	// create data
	Create(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	// read data
	Read(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
	// update data
	Update(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	// delete data
	Delete(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
}

type databaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseServiceClient(cc *grpc.ClientConn) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) Create(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/services.DatabaseService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) Read(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/services.DatabaseService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) Update(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/services.DatabaseService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) Delete(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/services.DatabaseService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
type DatabaseServiceServer interface {
	// create data
	Create(context.Context, *Data) (*Result, error)
	// read data
	Read(context.Context, *Data) (*Data, error)
	// update data
	Update(context.Context, *Data) (*Result, error)
	// delete data
	Delete(context.Context, *Data) (*Result, error)
}

func RegisterDatabaseServiceServer(s *grpc.Server, srv DatabaseServiceServer) {
	s.RegisterService(&_DatabaseService_serviceDesc, srv)
}

func _DatabaseService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DatabaseService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Create(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DatabaseService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Read(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DatabaseService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Update(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DatabaseService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Delete(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DatabaseService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _DatabaseService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DatabaseService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DatabaseService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database.proto",
}
